# Generated by Django 4.2.5 on 2024-06-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiringProject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IhaFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=150)),
                ('model', models.CharField(max_length=150)),
                ('weight', models.FloatField()),
                ('category', models.CharField(max_length=150)),
                ('communication_range', models.CharField(max_length=150)),
                ('wing_span', models.IntegerField()),
                ('take_off_and_landing', models.CharField(max_length=150)),
                ('payload_capacity', models.CharField(max_length=150)),
                ('thrust_type', models.CharField(max_length=150)),
                ('max_speed', models.BigIntegerField()),
                ('length', models.BigIntegerField()),
                ('operational_altitude', models.BigIntegerField()),
                ('isr', models.CharField(max_length=150)),
                ('hover_time', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
